include $(TOPDIR)/rules.mk

LUCI_TITLE:=youtubeUnblock luci application
LUCI_DEPENDS:=+youtubeUnblock +luci-compat

PKG_VERSION:=1.0.0
PKG_RELEASE:=1
PKG_LICENSE:=LICENSE

include $(TOPDIR)/feeds/luci/luci.mk
